- name: Run Tmate Debug Session  
  shell: bash  
  run: |  
    export PATH=$PATH:/c/msys64/usr/bin  
    export HOME=${GITHUB_WORKSPACE}  
    SOCKET_FILE=${GITHUB_WORKSPACE}/tmate.sock  
  
    echo "--- 1. Installing dependencies ---"  
    pacman -Sy --noconfirm --needed tmate curl jq || exit 1  
  
    echo "--- 2. Fetching SSH keys for ${{ github.actor }} ---"  
    mkdir -p ${HOME}/.ssh || exit 11  
    curl -s -H "Authorization: token ${{ github.token }}" \  
         "https://api.github.com/users/${{ github.actor }}/keys" | \  
         jq -r '.[].key' > ${HOME}/.ssh/authorized_keys || exit 12  
  
    echo "--- 3. Starting tmate session ---"  
    # Run synchronously, not backgrounded  
    tmate -S ${SOCKET_FILE} \  
      -a ${HOME}/.ssh/authorized_keys \  
      set-option -g status off \; \  
      set-option -g default-command "bash" \; \  
      new-session -d  
      
    # Wait for tmate to be ready (critical!)  
    tmate -S ${SOCKET_FILE} wait tmate-ready  
  
    echo "--- 4. Getting connection string ---"  
    TMATE_SSH=$(tmate -S ${SOCKET_FILE} display -p '#{tmate_ssh}')  
    echo "SSH: $TMATE_SSH"  
  
    echo "--- 5. Waiting for connection or exit signal ---"  
    while true; do  
      if [[ -f "${GITHUB_WORKSPACE}/continue" ]]; then  
        echo "Found 'continue' file. Ending tmate session."  
        break  
      fi  
      if [[ ! -e ${SOCKET_FILE} ]]; then  
        echo "Tmate session ended (socket file gone)."  
        break  
      fi  
      sleep 5  
    done  
  
    echo "--- 6. Cleanup ---"  
    tmate -S ${SOCKET_FILE} kill-session || echo "Tmate session already closed."
