name: 'No-Frills Tmate Session'
description: 'Starts a minimal tmate debug session for Windows with no status bar.'

inputs:
  timeout:
    description: 'Timeout in seconds AWAITING initial SSH connection.'
    required: false
    default: 300
  limit-access-to-actor:
    description: 'Ignored. Access is always limited to the actor.'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Run Tmate Debug Session
      # uses: humbletim/firestorm-gha/gha-node20-run@tpv-gha-nunja
      shell: bash
      run: inputs_timeout=${{ inputs.timeout }} ${{ github.action_path }}/action.bash  
