name: 'ReleaseFS_Open_Edge'
on:
  workflow_dispatch:
    inputs:
        artifact:
            type: string
        runner:
          required: true
          type: choice
          options:
            - windows-latest
            - ubuntu-latest
            - ubuntu-slim
            - macos-latest
          default: ubuntu-latest
        key:
            type: string
        tmate-followup:
            type: boolean
            default: false

run-name: ReleaseFS_Open Edge ${{ inputs.runner }} ${{ inputs.artifact }}

defaults:
  run:
    shell: bash

env:
  TZ: America/New_York

permissions:
  actions: write

jobs:
  debug:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/upload-artifact@v4
        if: false
      - name: Expose GitHub Runtime environment variables
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Output Inputs
        shell: bash
        run: |
          cat <<'EOF' | jq -c . | tee inputs.json
          ${{ toJSON(github.event.inputs) }}
          EOF

      - name: Checkout p373r-vrmod workspace
        shell: bash
        run: |
          git clone --quiet --filter=tree:0 --single-branch \
            https://github.com/humbletim/p373r-vrmod \
            --branch ${GITHUB_REF_NAME} p373r-vrmod \
          2>&1 | sed -E '/^(remote:|Receive|Resolve)/d'

      # memorialize the fstuple input for posterity; annotations seem survive longer (ie: > 6 months) than step summaries or raw logs
      - name: annotation
        shell: bash
        run: |
          echo "::notice title=inputs::$(jq -c . inputs.json)"
          echo "::notice title=mini-report::$(for id in `ls -1d p373r-vrmod 2>/dev/null` ; do
            echo -n "$(basename $id)=$(git -C $id rev-parse --short HEAD),$(git -C $id rev-list --count HEAD),$(git -C $id describe --all --always | sed 's@heads/@@'); "
          done)"

      - name: 'pip install pyyaml'
        if: startsWith(inputs.runner, 'windows-')
        shell: bash
        run: |
          pip install pyyaml

      - name: 'apt install clang-19 lld-19 python3-yaml'
        if: startsWith(inputs.runner, 'ubuntu-')
        shell: bash
        run: |
          echo apt update
          sudo apt update -qq -o=Dpkg::Use-Pty=0 2>&1 > /dev/null
          echo apt install gettext-base python3-yaml file eatmydata nano
          sudo apt install -y -qq -o=Dpkg::Use-Pty=0 gettext-base python3-yaml file eatmydata nano 2>&1 > /dev/null
          which clang-19 || {
            echo apt install clang-19 lld-19
            sudo eatmydata apt install -y -qq -o=Dpkg::Use-Pty=0 clang-19 lld-19 2>&1 > /dev/null
          }

          mkdir -pv bin
          wget https://github.com/bronze1man/yaml2json/releases/download/v1.3.5/yaml2json_linux_amd64 -O bin/yaml2json
          git clone https://github.com/humbletim/firestorm-gha tpv-gha-nunja --single-branch

      - name: 'xwin-ubuntu'
        if: startsWith(inputs.runner, 'ubuntu-')
        id: xwin-ubuntu
        uses: actions/cache/restore@v4
        with:
            path: bin/xwin
            key: ${{ inputs.runner }}-${{ inputs.key }}-xwin

      - name: ' ... xwin-ubuntu'
        id: xwin-ubuntu-fetch
        if: startsWith(inputs.runner, 'ubuntu-') && steps.xwin-ubuntu.outputs.cache-hit != 'true'
        shell: bash
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://github.com/Jake-Shadle/xwin/releases/download/0.8.0/xwin-0.8.0-x86_64-unknown-linux-musl.tar.gz
          mkdir -pv bin
          tar -C bin --wildcards --strip-components=1 -xvf xwin-0.8.0-x86_64-unknown-linux-musl.tar.gz \*/xwin
          # gh --repo humbletim/xwin run download --name xwin-ubuntu --dir bin
          # chmod a+x bin/xwin

      - name: '/xwin-ubuntu'
        if: startsWith(inputs.runner, 'ubuntu-') && steps.xwin-ubuntu.outputs.cache-hit != 'true' && steps.xwin-ubuntu-fetch.outcome == 'success'
        uses: actions/cache/save@v4
        with:
            path: bin/xwin
            key: ${{ steps.xwin-ubuntu.outputs.cache-primary-key }}

      - name: 'winsdk'
        if: startsWith(inputs.runner, 'ubuntu-')
        id: winsdk-ubuntu
        uses: actions/cache/restore@v4
        with:
            path: winsdk
            key: ${{ inputs.runner }}-${{ inputs.key }}-winsdk

      - name: ' ... winsdk-ubuntu'
        id: winsdk-ubuntu-fetch
        if: startsWith(inputs.runner, 'ubuntu-') && steps.winsdk-ubuntu.outputs.cache-hit != 'true'
        shell: bash
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -pv tmp
          SDKVER=10.0.26100
          CRTVER=14.44.17.14
          VARIANTS=desktop
          SDKROOT=winsdk
          bin/xwin --accept-license -Loff --cache-dir=tmp --variant $VARIANTS --crt-version $CRTVER --sdk-version $SDKVER splat --output $SDKROOT

      - name: '/winsdk-ubuntu'
        if: startsWith(inputs.runner, 'ubuntu-') && steps.winsdk-ubuntu.outputs.cache-hit != 'true' && steps.winsdk-ubuntu-fetch.outcome == 'success'
        uses: actions/cache/save@v4
        with:
            path: winsdk
            key: ${{ inputs.runner }}-${{ inputs.key }}-winsdk

      - name: ' ... winsdk-windows'
        id: winsdk-windows-emulate
        if: startsWith(inputs.runner, 'windows-')
        shell: bash
        run: |
          ./p373r-vrmod/experiments/winsdk.in/other/vs-emulate-xwin.bat

      - name: 'ARTIFACT:'
        id: artifact
        uses: actions/cache/restore@v4
        with:
            path: fs-open
            key: ${{ inputs.runner }}-${{ inputs.key }}-${{ inputs.artifact }}-artifact

      - name: '  download and unpack artifact'
        id: ghdl
        if: steps.artifact.outputs.cache-hit != 'true'
        shell: bash
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://github.com/humbletim/firestorm-gha/releases/download/v7.2.3-vr-alpha-0/fs-open-80036-afc53db-afc53db-devtime.zip
          unzip -q fs-open-80036-afc53db-afc53db-devtime.zip
          #gh --repo humbletim/firestorm-gha run download --name ${{inputs.artifact}} --dir _snapshot

      - name: '/ARTIFACT'
        if: always() && steps.artifact.outputs.cache-hit != 'true' && steps.ghdl.outcome == 'success'
        uses: actions/cache/save@v4
        with:
            path: fs-open
            key: ${{ steps.artifact.outputs.cache-primary-key }}

      - name: '  edge-compile new viewer exe'
        shell: bash
        run: |
          sudo mkdir /d
          ln -vsTf ~/work /d/a
          sudo mkdir -p '/c/Program Files/nodejs'
          ln -vsTf /usr/local/bin/node '/c/Program Files/nodejs/node'
          ln -vsTf /usr/lib/llvm-19 p373r-vrmod/llvm
          ln -vsTf $PWD/winsdk p373r-vrmod/winsdk
          touch winsdk/vfsoverlay.json 
          cd ./p373r-vrmod/community
          ../experiments/tpvm.sh init ../../fs-open
          ../experiments/tpvm.sh patch llviewerdisplay.cpp
          ../experiments/tpvm.sh mod lldir_win32.cpp
          ../experiments/tpvm.sh compile_ llviewerdisplay.cpp
          ../experiments/tpvm.sh compile_ lldir_win32.cpp
          ../experiments/tpvm.sh compile_ vrmod.llviewerdisplay.hpp 
          ../experiments/tpvm.sh compile_ llviewerVR.cpp 
          ../experiments/tpvm.sh compile_ ../asdf/humbletim/xopenvr.hpp
          ../experiments/tpvm.sh compile_ ../asdf/humbletim/opengl.hpp 
          ../experiments/tpvm.sh link

      - name: '  edge-compile new viewer exe'
        shell: bash
        run: |
          cd ./p373r-vrmod/community
          bash -c '. 3p-community-vrmod/improvise.bash ; provision_community_vrmod $PWD'          

      - name: '/UPLOAD'
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.runner }}-${{ inputs.key }}-3p-community-vrmod
            path: p373r-vrmod/community/community-vrmod-*.tar.*

      - name: '/UPLOAD 3p'
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.runner }}-${{ inputs.key }}-3p-community-vrmod
            path: p373r-vrmod/community/fs-open.exe

      - name: Setup no-frills tmate session
        if: failure() || inputs.tmate-followup && inputs.runner == 'windows-latest'
        uses: ./p373r-vrmod/.github/nofrills-tmate
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          limit-access-to-actor: true

      - name: Setup fallback tmate session
        if: failure() || inputs.tmate-followup
        uses: mxschmitt/action-tmate@v3
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          limit-access-to-actor: true
