name: 'ReleaseFS_Open_Edge'
on:
  workflow_dispatch:
    inputs:
        key:
          type: string
          default: ''
        runner:
          required: true
          type: choice
          options:
            - ubuntu-latest
            - ubuntu-slim
          default: ubuntu-latest
        executable:
            type: boolean
            default: true
        windows-toolchain:
            type: boolean
            default: false
        autobuild-package:
            type: boolean
            default: false
        screenshot:
            type: boolean
            default: false
        tmate-followup:
            type: boolean
            default: false

run-name: ReleaseFS_Open Edge ${{ inputs.runner }}

defaults:
  run:
    shell: bash

env:
  TZ: America/New_York
  CACHE_ID: ubuntu-latest-${{ inputs.key }}
  node: /usr/local/bin/node
  _actions: /home/runner/work/_actions

permissions:
  actions: write

jobs:
  debug:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: ensure actions/upload-artifact
        uses: actions/upload-artifact@v4
        if: false
      - name: ensure actions/cache
        uses: actions/cache@v4
        if: false

      - name: Output Inputs
        shell: bash
        run: |
          cat <<'EOF' | jq -c . | tee inputs.json
          ${{ toJSON(github.event.inputs) }}
          EOF

      - name: 'Checkout p373r-vrmod and ../tpv-gha-nunja workspace'
        shell: bash
        run: |
          clone() { git clone --no-progress --quiet --filter=tree:0 --single-branch "$@" ; }
          clone https://github.com/humbletim/p373r-vrmod --branch ${GITHUB_REF_NAME} ./p373r-vrmod
          clone https://github.com/humbletim/firestorm-gha ../tpv-gha-nunja
          ln -s ../tpv-gha-nunja/gha-node20-run

      - name: preflight check
        uses: ./gha-node20-run
        env:
          DEBUG: true
        with:
          run: echo "hi from within node-20-run!"

      # memorialize the fstuple input for posterity; annotations seem survive longer (ie: > 6 months) than step summaries or raw logs
      - name: annotation
        shell: bash
        run: |
          echo "::notice title=inputs::$(jq -c . inputs.json)"
          echo "::notice title=mini-report::$(for id in `ls -1d p373r-vrmod 2>/dev/null` ; do
            echo -n "$(basename $id)=$(git -C $id rev-parse --short HEAD),$(git -C $id rev-list --count HEAD),$(git -C $id describe --all --always | sed 's@heads/@@'); "
          done)"

      - name: 'misc'
        shell: bash
        run: |
          which file 2>/dev/null || ./p373r-vrmod/experiments/portables/setup-ubuntu-build-deps.bash
          mkdir -pv bin
          wget -q -nv https://github.com/bronze1man/yaml2json/releases/download/v1.3.5/yaml2json_linux_amd64 -O bin/yaml2json \
            && chmod a+x bin/yaml2json

      - name: 'LLVM 19'
        if: inputs.executable
        shell: bash
        run: |
          which clang++19 2>/dev/null || ./p373r-vrmod/experiments/portables/portable-clang++.bash
          ln -vsTf /usr/lib/llvm-19 llvm

      - name: CACHED-winsdk
        uses: ./gha-node20-run
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.cachette.bash

            gha-cache-restore-fast "$CACHE_ID-winsdk" "$(echo "winsdk" | tr ' ' '\n')" || (
              ./p373r-vrmod/experiments/portables/portable-winsdk.bash || exit 178
              gha-cache-save-fast "$CACHE_ID-winsdk" "$(echo "winsdk" | tr ' ' '\n')" || exit 179 
            )

      - name: CACHED-fs-open-devtime
        uses: ./gha-node20-run
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.cachette.bash

            gha-cache-restore-fast "$CACHE_ID--artifact" "$(echo "fs-open" | tr ' ' '\n')" || (
              wget -nv https://github.com/humbletim/firestorm-gha/releases/download/v7.2.3-vr-alpha-0/fs-open-80036-afc53db-afc53db-devtime.zip \
                && unzip -q fs-open-80036-afc53db-afc53db-devtime.zip \
                || exit 178
              gha-cache-save-fast "$CACHE_ID--artifact" "$(echo "fs-open" | tr ' ' '\n')" || exit 179 
            )

      - name: '  edge-compile new viewer exe'
        if: inputs.executable
        shell: bash
        run: |
          cd ./p373r-vrmod/community
          ../experiments/tpvm.sh init ../../fs-open
          ../experiments/tpvm.sh patch llviewerdisplay.cpp
          ../experiments/tpvm.sh mod lldir_win32.cpp
          make fs-open.exe -j

      - name: '/UPLOAD viewer .exe'
        uses: ./gha-node20-run
        if: inputs.executable
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
            gha-upload-artifact-fast \
              fs-${{ inputs.key }}-community-vrmod-exe \
              p373r-vrmod/community/fs-open.exe 1 9 || exit 150

      - name: '3p-community-vrmod autobuild-package'
        uses: ./gha-node20-run
        if: inputs.autobuild-package
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
            cd ./p373r-vrmod/community
            bash -c '. 3p-community-vrmod/improvise.bash ; provision_community_vrmod $PWD'
            gha-upload-artifact-fast \
              fs-${{ inputs.key }}-3p-community-vrmod-autobuild-package \
              community-vrmod-*.tar.bz2 || exit 150

      - name: CACHED-official-runtime
        uses: ./gha-node20-run
        if: inputs.executable && inputs.screenshot
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.cachette.bash

            gha-cache-restore-fast "$CACHE_ID-runtime" "$(echo "official" | tr ' ' '\n')" || (
              wget -nv https://downloads.firestormviewer.org/release/windows/Phoenix-FirestormOS-Releasex64_AVX2-7-2-3-80036_Setup.exe \
                && 7z -bd -bb0 -oofficial x Phoenix-FirestormOS-Releasex64_AVX2-7-2-3-80036_Setup.exe \
                || exit 178
              gha-cache-save-fast "$CACHE_ID-runtime" "$(echo "official" | tr ' ' '\n')" || exit 179
            )
            # ( cd fs-open && ln -vsTf ../official runtime )

      - name: wine/xvfb/screenshot stuff
        uses: ./gha-node20-run
        if: inputs.executable && inputs.screenshot
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
            ./p373r-vrmod/experiments/portables/setup-ubuntu-xvfb.bash
            wine --version
            cd p373r-vrmod/community
            TIMEOUT=60 WINEPATH=../../official ../asdf/manual_screenshot.sh || true
            gha-upload-artifact-fast screenshot-region screenshot-region.jpg || exit 150

      - name: inputs.windows-toolchain
        uses: ./gha-node20-run
        if: inputs.windows-toolchain
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
            function provision_devspace() {(
              set -Euo pipefail
              mkdir -pv devspace/ devspace/bin #devspace/winsdk
              test ! -d devspace/pg && wget -q -nv https://github.com/git-for-windows/git/releases/download/v2.53.0.windows.1/PortableGit-2.53.0-64-bit.7z.exe \
                && 7z -bd -bb0 -odevspace/pg x PortableGit-2.53.0-64-bit.7z.exe
              test ! -d devspace/clang+llvm-19.1.0-x86_64-pc-windows-msvc.tar.xz \
                && wget -O devspace/clang+llvm-19.1.0-x86_64-pc-windows-msvc.tar.xz -q -nv https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.0/clang+llvm-19.1.0-x86_64-pc-windows-msvc.tar.xz
                # && xz -d -c clang+llvm-19.1.0-x86_64-pc-windows-msvc.tar.xz | tar -xf - -Cdevspace/llvm --strip-components=1
              test ! -s devspace/bin/ninja.exe && wget -q -nv https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip \
                && 7z -bd -bb0 -odevspace/bin x ninja-win.zip
              test ! -s devspace/bin/jq.exe && wget -O devspace/bin/jq.exe -q -nv https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-windows-amd64.exe
              test ! -s devspace/python/python.exe && wget -q -nv https://www.python.org/ftp/python/3.14.3/python-3.14.3-embed-amd64.zip \
                && unzip -d devspace/python python-3.14.3-embed-amd64.zip
              test ! -d devspace/p373r-vrmod && git -C p373r-vrmod worktree add $PWD/devspace/p373r-vrmod --force

              # test ! -s devspace/bin/xwin.exe && wget -q -nv https://github.com/Jake-Shadle/xwin/releases/download/0.8.0/xwin-0.8.0-x86_64-pc-windows-msvc.tar.gz \
                # && tar -xf xwin-0.8.0-x86_64-pc-windows-msvc.tar.gz -Cdevspace/bin --strip-components=1 xwin-0.8.0-x86_64-pc-windows-msvc/xwin.exe
              # test ! -s devspace/winsdk.tar.xz && XZ_OPT='-T0' tar -cJf devspace/winsdk.tar.xz winsdk
              test ! -d devspace/winsdk/crt && mkdir -pv devspace/winsdk && sudo mount -o bind winsdk devspace/winsdk

              cd devspace/
              (
                echo "experimental toolchain capture"
                date --rfc-3339 seconds
                echo ''
                echo '```sh'
                echo 'cd p373r-vrmod/community'
                echo 'env PYTHONEXECUTABLE=../../python/python.exe WINSDK_DIR=../../winsdk LLVM_DIR=../../llvm ../experiments/tpvm.sh init [fs-open-devtime]'
                echo '../experiments/tpvm.sh compile_ llviewerdisplay.cpp lldir_win32.cpp vrmod.llviewerdisplay.hpp llviewerVR.cpp ../asdf/humbletim/opengl.hpp ../asdf/humbletim/xopenvr.hpp'
                echo '../experiments/tpvm.sh link'
                echo 'PATH=[factory_runtime] ./fs-open.exe'
                echo '```'
                echo ''
                echo "see $GITHUB_WORKFLOW_REF"
                echo ''
                echo -n 'p373r-vrmod: ' && git -C p373r-vrmod describe --all
                echo ''
                echo '```bash'
                declare -pf provision_devspace
                echo '```'
              ) > readme.md
              du -hsc *
            )}
            provision_devspace

      - name: upload windows-toolchain (?)
        uses: ./gha-node20-run
        if: inputs.windows-toolchain
        with:
          run: |
            set -Euo pipefail
            source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
            cd devspace/ && gha-upload-artifact-fast windows-toolchain . 1 9

      # - name: upload windows-toolchain a (~5.5GB)
      #   uses: ./gha-node20-run
      #   if: inputs.windows-toolchain
      #   with:
      #     run: |
      #       set -Euo pipefail
      #       source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
      #       cd devspace/ && 7z -bd -bb0 -bt -tzip a ../windows-toolchain.zip .
      #       zipUploadStream=windows-toolchain.zip gha-upload-artifact-fast windows-toolchain-a /dev/null

      # - name: upload windows-toolchain b (~1GB)
      #   uses: ./gha-node20-run
      #   if: inputs.windows-toolchain
      #   with:
      #     run: |
      #       set -Euo pipefail
      #       source ../tpv-gha-nunja/gha/gha.upload-artifact.bash
      #       cp -av clang*.tar.xz devtime/
      #       cd devspace/ && 7z -bd -bb0 -bt -t7z a ../windows-toolchain.7z .
      #       gha-upload-artifact-fast windows-toolchain-b windows-toolchain.7z

      - name: Setup no-frills tmate session
        if: failure() || inputs.tmate-followup
        uses: ./gha-node20-run
        with:
          run: ./p373r-vrmod/.github/nofrills-tmate/action.bash

      - name: Setup fallback tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
